### ISSUE TITLE
Feature request: show icon/logo of bookmarked page

### ISSUE THREAD

**Issue by cipricus** [lucaseverett/easy-speed-dial#39]
One thing that I miss is the clear logo of something like youtube or gmail, instead of just color.

![image](https://user-images.githubusercontent.com/3447868/196631442-a1c06d95-e1ed-491b-9cad-40d7bab1bf82.png)

**Comment by Sowhaaat** [comment]
Supporting that option too, giving the choice to add our own icons either manually, using a browser build-in screenshot tool or usuing an external service (miniature.io, thum.io) would be great.

Given the privacy-first focus it would be awesome to have at least either a manual option or a way to refresh the link text with images.

This extension is probably gonna have new users from several extensions that are not working or are not maintained anymore like Simple Speed Dial on Chrome browsers, Toolbar Dial is rare extensions to support folders.

Great work BTW!

**Comment by lucaseverett** [comment]
Closed by e5d8667dd4dafddd6ea5d48cab50138c97568653.
