### ISSUE TITLE
Feature: Manually set colors for specific domains/subdomains

### ISSUE THREAD

**Issue by raniesantos** [lucaseverett/easy-speed-dial#42]
The colors are automatic, so sometimes it defaults to a very mismatched color for specific sites.

For example, I get blue for MEGA.nz but clearly their branding uses the color red.

I get purple for GitHub but that color belongs to GitLab. I want to change it to a dark shade of gray.

That's only two examples, but I think you get the point.

I see that you have a color list coded into `dialColors.js`, but that means users have to bother you, pray that it doesn't take you forever to see it, wait for you to have free time to add the code, and then wait for the update to get pushed to Chrome Web Store. It would be convenient for both parties if this option just existed.

**Comment by lucaseverett** [comment]
@raniesantos The demo version now has a beta test for the custom dial color functionality. Please let me know if you have any thoughts or feedback. This will be in the upcoming January update of Toolbar Dial.

https://demo-beta.toolbardial.com/

**Comment by lucaseverett** [comment]
Custom dial colors feature added in d89ad0f997838b54d6c50a5cb536639655e48cce.

**Comment by sudoshindo** [comment]
https://github.com/lucaseverett/easy-speed-dial/assets/97193233/e0adbf63-13f0-4781-b30e-85bdb72556e4

feature is bugged, this recording is of the firefox version of the extension

**Comment by lucaseverett** [comment]
Thank you for letting me know about this issue. This has been fixed in the 2.8.1 that is now available for Firefox.

**Comment by sudoshindo** [comment]
Wasn't able to test it on Chromium browsers but I assume you already had that covered before the 2.8 release.

**Comment by lucaseverett** [comment]
The same code is used for both Chrome and Firefox, and this was only happening with Firefox. I don't know if it's a bug with Firefox or just a difference in how they implemented cloning a proxy object when using the storage functionality. I made a note of it so I'll remember that Firefox has to be handled differently when saving the dial color.
