### ISSUE TITLE
[Feature request] Generate "thumbnail" via favicon option for tiles

### ISSUE THREAD

**Issue by PikachuEXE** [lucaseverett/easy-speed-dial#52]
I have read https://github.com/lucaseverett/easy-speed-dial/issues/14 & https://github.com/lucaseverett/easy-speed-dial/issues/28 also the [permissions doc](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions)

I wonder if `tabs` permission along with `Tab.faviconUrl` can be used to generate thumbnail from favicons (at least it looks better than just URL)

> tabs gives you access to [privileged parts of the tabs API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs) without the need for [host permissions](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#host_permissions): Tab.url, Tab.title, and Tab.faviconUrl.

**Comment by lucaseverett** [comment]
Thank you for the suggestion. At this time I don't plan to add that as a feature.
