### ISSUE TITLE
Backup and Restore - not restoring custom dial colors

### ISSUE THREAD

**Issue by Armikas** [lucaseverett/easy-speed-dial#53]
Hello, 

I`m using one of my bookmarks folder dedicated (Bookmarks bar/Start) for spead dial. 
Tried to do backup and restore it to anotker PC (Google Chome Sync is ON on both computers with same account), but custom dial collors and prefered bookmarks dial folder not restored.

Also would be nice to be able to exclude background setting from backup.

**Comment by lucaseverett** [comment]
Hi, @Armikas. Thank you for the feedback. Each computer/profile has different bookmark IDs. Unfortunately, there isn't a way to use a backup for a different computer. Backups are intended for use as a restore point for your current profile. I would need to use a back end server to sync for that to work, which goes against the mission of using browser bookmarks with no syncing for privacy.
